enum CATEGORY {
  'General Knowledge' = 25,
  'Entertainment: Books' = 26,
  'Entertainment: Film' = 27,
  'Entertainment: Music' = 28,
  'Entertainment: Musicals & Theatres' = 29,
  'Entertainment: Television' = 30,
  'Entertainment: Video Games' = 31,
  'Entertainment: Board Games' = 32,
  'Science & Nature' = 33,
  'Science: Computers' = 34,
  'Science: Mathematics' = 35,
  'Mythology' = 36,
  'Sports' = 37,
  'Geography' = 38,
  'History' = 39,
  'Politics' = 40,
  'Art' = 41,
  'Celebrities' = 42,
  'Animals' = 43,
  'Vehicles' = 44,
  'Entertainment: Comics' = 45,
  'Science: Gadgets' = 46,
  'Entertainment: Japanese Anime & Manga' = 47,
  'Entertainment: Cartoon & Animations' = 48,
}

export default CATEGORY;
